# Generated by Django 5.2.11 on 2026-02-20 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileactivity',
            options={'ordering': ('priority',)},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='activity',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='profiles', through='profiles.ProfileActivity', to='profiles.activity'),
        ),
        migrations.AlterField(
            model_name='profileactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_activity', to='profiles.activity'),
        ),
        migrations.AlterField(
            model_name='profileactivity',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_activity', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfileVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_visa', to='profiles.userprofile')),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_visa', to='countries.visatype')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visa',
            field=models.ManyToManyField(blank=True, related_name='profiles', through='profiles.ProfileVisa', to='countries.visatype'),
        ),
    ]
