# Generated by Django 5.2.11 on 2026-02-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profileactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='budget_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='budget_min',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
