# Generated by Django 5.2.11 on 2026-02-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_budget_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activities',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', through='profiles.ProfileActivity', to='profiles.activity'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='budget_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
